---
- name: Setup br-ex bridge on nodes
  hosts: all
  become: true
  serial: 1  # One node at a time for safety

  tasks:
    - name: Update apt cache
      apt:
        update_cache: no

    - name: Install openvswitch-switch
      apt:
        name: openvswitch-switch
        state: present

    - name: Ensure openvswitch-switch service is running
      service:
        name: openvswitch-switch
        state: started
        enabled: yes

    - name: Check if br-ex bridge exists
      command: ovs-vsctl br-exists {{ bridge_name }}
      register: bridge_check
      failed_when: false
      changed_when: false

    - name: Create OVS bridge if not exists
      command: ovs-vsctl add-br {{ bridge_name }}
      when: bridge_check.rc != 0

    - name: Check if physical interface is port of bridge
      command: ovs-vsctl port-to-br {{ physical_interface }}
      register: port_check
      failed_when: false
      changed_when: false

    - name: Add physical port to OVS bridge if not added
      command: ovs-vsctl add-port {{ bridge_name }} {{ physical_interface }}
      when: port_check.rc != 0 or port_check.stdout != bridge_name

    - name: Create persistent Netplan config for OVS bridge
      template:
        src: netplan_template.j2
        dest: /etc/netplan/50-br-ex-config.yaml
        mode: 0644
      notify: Apply Netplan and verify

  handlers:
    - name: Apply new network config
      command: netplan apply
      listen: Apply Netplan and verify

    - name: Pause for network to settle
      pause:
        seconds: 5
      listen: Apply Netplan and verify

    - name: Verify public connectivity
      command: ping -c 3 8.8.8.8
      changed_when: false
      listen: Apply Netplan and verify

    - name: Ensure private interface is up
      command: ip link show {{ physical_interface }}.1871
      changed_when: false
      listen: Apply Netplan and verify